spring:
  application:
    name: service-b

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/demo

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development

  otlp:
    metrics:
      export:
        url: http://lgtm-gateway.observability:4317
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://lgtm-gateway.observability:4317
    logging:
      export:
        otlp:
          endpoint: http://lgtm-gateway.observability:4317

service:
  name: "Service B"
  description: "Demo service"
  version: "0.0.1"