spring:
  application:
    name: service-b

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/demo

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  tracing:
    sampling:
      probability: 1.0

service:
  name: "Service B"
  description: "Demo service"
  version: "0.0.1"