apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: keycloak
      version: "25.3.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    image:
      repository: bitnamilegacy/keycloak
#      tag: 23.0.7-debian-12-r4
      tag: latest

    auth:
      adminUser: keycloak
      adminPassword: keycloak   # ⚠️ vervangen via secret in productie

    proxy: edge

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: keycloak.local
      path: /
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /

    postgresql:
      enabled: true
      image:
        repository: bitnamilegacy/postgresql
        tag: latest
#        tag: 17.6.0-debian-12-r0

      auth:
        postgresPassword: keycloak
        username: keycloak
        password: keycloak
        database: keycloak

      primary:
        persistence:
          enabled: true
          size: 1Gi

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false