apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.jetstack.io
---
# Defines the OCI Helm repository where the Bitnami PostgreSQL chart is hosted
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  type: oci
  # Bitnami OCI registry for Helm charts
  url: oci://registry-1.docker.io/bitnamicharts
  interval: 1h  # How often Flux checks for new chart versions
