apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepositories.yaml
  - cert-manager.yaml
  - cert-manager-namespace.yaml
  - keycloak.yaml
  - keycloak-namespace.yaml
  - postgresql.yaml
  - postgresql-namespace.yaml