image:
  repository: agilesolutions/service-a
  tag: 0.0.1

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: service-a.local

config:
  featureToggle: true
  maxOrders: 100

oidc:
  clientId: service-a
  clientSecret: lvmDY4QItURQCBL8Ax4MhGGNKQSAKxrB
  tokenUri: http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/demo/protocol/openid-connect/token