image:
  repository: agilesolutions/service-b
  tag: 0.0.1

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: service-b.local

config:
  featureToggle: true
  maxOrders: 100

oauth2:
  issuerUri: http://keycloak-keycloakx-http.keycloak.svc.cluster.local/realms/demo
