apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-config
data:
  application.yaml: |
    app:
      featureToggle: {{ .Values.config.featureToggle }}
      maxOrders: {{ .Values.config.maxOrders }}