apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap
data:
  application.yaml: |
    app:
      featureToggle: {{ .Values.config.featureToggle }}
      maxOrders: {{ .Values.config.maxOrders }}
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.oauth2.issuerUri }}
